language: python
sudo: false
cache: pip

jobs:
  fast_finish: true
  include:
    - env: TOXENV=flake8

    - env: TOXENV=mypy

    - env: TOXENV=pypy3
      python: pypy3

    - env: TOXENV=py35
      after_success: &after_success
        - pip install coveralls
        - coveralls

    - env: TOXENV=py36
      python: "3.6"
      after_success: *after_success

    - env: TOXENV=py37
      python: "3.7-dev"
      after_success: *after_success

python: "3.5.2"

install:
  - pip install "setuptools >= 36.2.7"
  - pip install tox

script: tox
